export const schema = [
  {
    table_name: "attendance",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "crew_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "date", type: "date", is_nullable: "NO", required: true },
      { name: "status", type: "text", is_nullable: "NO", required: true },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
      { name: "present", type: "integer", is_nullable: "YES", required: false },
      { name: "absent", type: "integer", is_nullable: "YES", required: false },
      { name: "late", type: "integer", is_nullable: "YES", required: false },
      { name: "total", type: "integer", is_nullable: "YES", required: false },
    ],
  },
  {
    table_name: "budgets",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "department", type: "text", is_nullable: "NO", required: true },
      { name: "allocated", type: "bigint", is_nullable: "NO", required: true },
      { name: "spent", type: "bigint", is_nullable: "NO", required: true },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
    ],
  },
  {
    table_name: "crew",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "name", type: "text", is_nullable: "NO", required: true },
      { name: "role", type: "text", is_nullable: "NO", required: true },
      { name: "department", type: "text", is_nullable: "NO", required: true },
      { name: "status", type: "text", is_nullable: "YES", required: false },
      { name: "available", type: "text", is_nullable: "YES", required: false },
      { name: "contact", type: "text", is_nullable: "YES", required: false },
      { name: "duration", type: "text", is_nullable: "YES", required: false },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
    ],
  },
  {
    table_name: "dailies",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "gen_random_uuid()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "scene_id", type: "integer", is_nullable: "NO", required: true },
      {
        name: "takes",
        type: "integer",
        is_nullable: "NO",
        default: "0",
        required: false,
      },
      {
        name: "approved",
        type: "integer",
        is_nullable: "NO",
        default: "0",
        required: false,
      },
      {
        name: "review",
        type: "integer",
        is_nullable: "NO",
        default: "0",
        required: false,
      },
      {
        name: "retake",
        type: "integer",
        is_nullable: "NO",
        default: "0",
        required: false,
      },
      {
        name: "director_status",
        type: "text",
        is_nullable: "NO",
        default: "'Pending'::text",
        required: false,
      },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "YES",
        default: "CURRENT_TIMESTAMP",
        required: false,
      },
    ],
  },
  {
    table_name: "deliverables",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "name", type: "text", is_nullable: "NO", required: true },
      { name: "type", type: "text", is_nullable: "NO", required: true },
      { name: "status", type: "text", is_nullable: "NO", required: true },
      { name: "due_date", type: "date", is_nullable: "NO", required: true },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
    ],
  },
  {
    table_name: "departments",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "gen_random_uuid()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "YES", required: false },
      { name: "name", type: "text", is_nullable: "YES", required: false },
      { name: "lead", type: "text", is_nullable: "YES", required: false },
      { name: "budget", type: "numeric", is_nullable: "YES", required: false },
      {
        name: "head_count",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
      { name: "status", type: "text", is_nullable: "YES", required: false },
    ],
  },
  {
    table_name: "equipment",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "gen_random_uuid()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "YES", required: false },
      { name: "name", type: "text", is_nullable: "YES", required: false },
      { name: "unit", type: "text", is_nullable: "YES", required: false },
      { name: "status", type: "text", is_nullable: "YES", required: false },
      { name: "condition", type: "text", is_nullable: "YES", required: false },
    ],
  },
  {
    table_name: "invoices",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "vendor", type: "text", is_nullable: "NO", required: true },
      { name: "amount", type: "bigint", is_nullable: "NO", required: true },
      { name: "status", type: "text", is_nullable: "NO", required: true },
      { name: "date_issued", type: "date", is_nullable: "NO", required: true },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
      {
        name: "due_date",
        type: "timestamp without time zone",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "delay_days",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
    ],
  },
  {
    table_name: "locations",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      { name: "name", type: "text", is_nullable: "NO", required: true },
      { name: "type", type: "text", is_nullable: "NO", required: true },
      { name: "cost", type: "bigint", is_nullable: "NO", required: true },
      { name: "status", type: "text", is_nullable: "NO", required: true },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
    ],
  },
  {
    table_name: "milestones",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "gen_random_uuid()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "YES", required: false },
      { name: "milestone", type: "text", is_nullable: "YES", required: false },
      { name: "status", type: "text", is_nullable: "YES", required: false },
      {
        name: "progress",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "target_date",
        type: "timestamp without time zone",
        is_nullable: "YES",
        required: false,
      },
    ],
  },
  {
    table_name: "payroll",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "gen_random_uuid()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "YES", required: false },
      { name: "category", type: "text", is_nullable: "YES", required: false },
      { name: "amount", type: "numeric", is_nullable: "YES", required: false },
      { name: "status", type: "text", is_nullable: "YES", required: false },
      {
        name: "due_date",
        type: "timestamp without time zone",
        is_nullable: "YES",
        required: false,
      },
    ],
  },
  {
    table_name: "projects",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "name", type: "text", is_nullable: "NO", required: true },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
      { name: "start_date", type: "date", is_nullable: "YES", required: false },
      { name: "end_date", type: "date", is_nullable: "YES", required: false },
      {
        name: "total_budget",
        type: "bigint",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "days_in_production",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "scenes_completed",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "total_scenes",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "team_members",
        type: "integer",
        is_nullable: "YES",
        required: false,
      },
    ],
  },
  {
    table_name: "schedules",
    columns: [
      {
        name: "id",
        type: "uuid",
        is_nullable: "NO",
        default: "uuid_generate_v4()",
        required: false,
      },
      { name: "project_id", type: "uuid", is_nullable: "NO", required: true },
      {
        name: "description",
        type: "text",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "planned_start",
        type: "timestamp without time zone",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "planned_end",
        type: "timestamp without time zone",
        is_nullable: "YES",
        required: false,
      },
      {
        name: "progress",
        type: "integer",
        is_nullable: "YES",
        default: "0",
        required: false,
      },
      {
        name: "created_at",
        type: "timestamp with time zone",
        is_nullable: "NO",
        default: "now()",
        required: false,
      },
    ],
  },
];
